### ISSUE TITLE
Bug: CMS image upload not working

### ISSUE THREAD

**Issue by kcullion** [nci-hcmi-catalog/portal#589] opened 2020-05-13 16:43 UTC
On the test CMS site, when I go to my model to upload images, dragging and dropping images doesn't do anything. 

When I browse to the images on my desktop and click upload, nothing happens.

**Comment by rosibaj** [comment] 2020-05-14 17:44
@kcullion this works for me - is this still happening to you?

**Comment by kcullion** [comment] 2020-05-14 17:51
@rosibaj I see your images...but I tried in this model: http://hcmi.cancercollaboratory.org/admin/model/HCM-BEAR-0001-C17

And can't seem to get images to upload

**Comment by rosibaj** [comment] 2020-05-14 17:55
@kcullion i added a image to that one (not published).  are you able to upload one now?

**Comment by kcullion** [comment] 2020-05-14 18:23
@rosibaj yes I seem to be able to add images to the ones you already added to. Let me try making a new model and adding images. 
It does take a while for the image to be added did we used to have a loader to show something is happening?

**Comment by rosibaj** [comment] 2020-05-14 19:30
@kcullion it shouldnt be taking that long.... seems something is different on your computer.  Were you ever able to successfully add the first image?

**Comment by kcullion** [comment] 2020-05-14 19:46
Yes whenever I try to add images to a model that doesn't have images, nothing happens and I get this error:

<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>

**Comment by akachru-github** [comment] 2020-05-19 14:07
Not reproducible by anyone other than @kcullion .

**Comment by rosibaj** [comment] 2020-05-26 00:23
Closing as not reproducible.

**Closed by rosibaj** 2020-05-26 00:23 UTC
Labels: Scope Change, bug

**Comment by kcullion** [comment] 2020-05-26 13:31
update: I can upload images now. Must have been Ilderton
